Repository gardener/external-dns-management, pull requests merged in 2020-11, with the labels that each got.

#135 Don't set new DNSEntry to invalid if DNSOwner is pending
  pkg/dns/provider/entry.go
  pkg/dns/provider/ownercache.go
  pkg/dns/provider/state.go
  pkg/dns/provider/state_owner.go
  pkg/dns/provider/state_zone.go
Labels: needs/ok-to-test, needs/review, size/s

#136 set finalizer immediately when entry becomes valid
  pkg/dns/provider/state_entry.go
Labels: kind/bug, needs/ok-to-test, size/xs

#137 optional default TTL per provider
  charts/external-dns-management/templates/crds.yaml
  docs/usage/dnsprovider_status.md
  examples/10-crds.yaml
  examples/11-crd-dnspr-val.yaml
  examples/30-provider-aws.yaml
  examples/controller-registration.yaml
  pkg/apis/dns/crds/dns.gardener.cloud_dnsproviders.yaml
  pkg/apis/dns/crds/zz_generated_crds.go
  pkg/apis/dns/v1alpha1/dnsprovider.go
  pkg/apis/dns/v1alpha1/zz_generated.deepcopy.go
  pkg/dns/provider/entry.go
  pkg/dns/provider/interface.go
  pkg/dns/provider/provider.go
  pkg/dns/provider/state.go
  pkg/dns/provider/state_provider.go
Labels: kind/api-change, needs/ok-to-test, needs/second-opinion, size/s

#139 Environment variables configurable in values-file of Helm
  charts/external-dns-management/templates/deployment.yaml
  charts/external-dns-management/values.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#138 additional printer columns
  charts/external-dns-management/templates/crds.yaml
  examples/10-crds.yaml
  examples/11-crd-dnse-val.yaml
  examples/11-crd-dnspr-val.yaml
  examples/controller-registration.yaml
  pkg/apis/dns/crds/dns.gardener.cloud_dnsentries.yaml
  pkg/apis/dns/crds/dns.gardener.cloud_dnsowners.yaml
  pkg/apis/dns/crds/dns.gardener.cloud_dnsproviders.yaml
  pkg/apis/dns/crds/zz_generated_crds.go
  pkg/apis/dns/v1alpha1/dnsentry.go
  pkg/apis/dns/v1alpha1/dnsowner.go
  pkg/apis/dns/v1alpha1/dnsprovider.go
Labels: kind/api-change, needs/ok-to-test, needs/second-opinion, size/l
