Repository gardener/external-dns-management, pull requests merged in 2020-08, with the labels that each got.

#110 typo
  doc/infoblox/README.md
Labels: needs/ok-to-test, reviewed/lgtm

#109 Set revisionHistoryLimit to 0 for deployment in chart
  charts/external-dns-management/templates/deployment.yaml
Labels: kind/cleanup, needs/ok-to-test, reviewed/lgtm

#114 VerticalPodAutoscaler defintion for dns-controller-manager
  charts/external-dns-management/templates/deployment.yaml
  charts/external-dns-management/templates/vpa.yaml
  charts/external-dns-management/values.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#115 Faster recovery if zones request fails temporarily and some fine tuning
  pkg/dns/provider/ownercache.go
  pkg/dns/provider/ownercache_test.go
  pkg/dns/provider/state_entry.go
  pkg/dns/provider/state_owner.go
  pkg/dns/provider/state_zone.go
  pkg/dns/provider/zonecache.go
Labels: needs/ok-to-test

#116 Keep finalizer for DNSEntry if its DNSProvider is not ready
  charts/external-dns-management/templates/clusterrole.yaml
  pkg/dns/provider/entry.go
  pkg/dns/provider/interface.go
  pkg/dns/provider/provider.go
  pkg/dns/provider/selection/selection.go
  pkg/dns/provider/state.go
  pkg/dns/provider/state_entry.go
  pkg/dns/provider/state_zone.go
  test/integration/singleEntryOneProvider_test.go
Labels: needs/ok-to-test

#117 fix CRDs + Ready-Stale transition
  -
  go.mod
  go.sum
  pkg/apis/dns/crds/dns.gardener.cloud_dnsannotations.yaml
  pkg/apis/dns/crds/dns.gardener.cloud_dnsentries.yaml
  pkg/apis/dns/crds/dns.gardener.cloud_dnsowners.yaml
  pkg/apis/dns/crds/dns.gardener.cloud_dnsproviders.yaml
  pkg/apis/dns/crds/zz_generated_crds.go
  pkg/apis/dns/v1alpha1/dnsowner.go
  pkg/dns/provider/entry.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/config/config.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controllermanager.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/definition.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/extension/extension.go
  vendor/github.com/gardener/controller-manager-library/pkg/resources/apiextensions/crds.go
  vendor/github.com/gardener/controller-manager-library/pkg/resources/apiextensions/deprecated.go
  vendor/github.com/gardener/controller-manager-library/pkg/resources/apiextensions/versions.go
  vendor/modules.txt
Labels: needs/ok-to-test, reviewed/lgtm

#118 new options for chart + support controller registration on vanilla images
  Makefile
  README.md
  charts/external-dns-management/templates/crds.yaml
  charts/external-dns-management/templates/deployment.yaml
  charts/external-dns-management/values.yaml
  examples/10-crds.yaml
  examples/controller-registration.yaml
  go.mod
  go.sum
  hack/generate-controller-registration.sh
  hack/generateChartOptions.py
  hack/install-requirements.sh
  pkg/dns/provider/errors/errors.go
  pkg/dns/provider/state_entry.go
  vendor/github.com/gardener/controller-manager-library/pkg/resources/apiextensions/crds.go
  vendor/modules.txt
Labels: needs/ok-to-test
