Repository gardener/external-dns-management, pull requests merged in 2020-07, with the labels that each got.

#92 fixed foreign sub domain in zone selection
  pkg/dns/provider/ownercache_test.go
  pkg/dns/provider/provider.go
  pkg/dns/provider/selection/selection.go
  pkg/dns/provider/selection/selection_suite_test.go
  pkg/dns/provider/selection/selection_test.go
  pkg/dns/provider/utils.go
  test/integration/singleEntryOneProvider_test.go
Labels: area/quality, area/robustness, needs/ok-to-test, priority/normal

#94 restrict number of CNAME targets
  pkg/dns/provider/entry.go
Labels: needs/ok-to-test

#97 fix dnsannotations crd in helm charts
  charts/external-dns-management/templates/crds.yaml
Labels: needs/ok-to-test

#99 Nit: Remove hack/code-generator/generate-groups.sh
  hack/code-generator/generate-groups.sh
Labels: kind/cleanup, needs/ok-to-test, reviewed/lgtm

#100 fix for rescheduling hosted zone
  pkg/dns/provider/state.go
  pkg/dns/provider/state_zone.go
  pkg/dns/utils/ratelimiter.go
Labels: needs/ok-to-test

#101 fix source DNSEntry references and dnsannotations update
  Makefile
  examples/41-entry-reference.yaml
  examples/70-dnsannotation.yaml
  go.mod
  go.sum
  pkg/controller/annotation/annotations/state.go
  pkg/controller/source/dnsentry/handler.go
  pkg/dns/source/reconciler.go
  pkg/dns/source/state.go
  vendor/modules.txt
Labels: needs/ok-to-test

#104 fix addallsplitted in controller-manager-library
  go.mod
  go.sum
  vendor/github.com/gardener/controller-manager-library/pkg/utils/stringset.go
  vendor/modules.txt
Labels: needs/ok-to-test

#105 Remove the duplicate ControllerRegistration under examples/
  .ci/prepare_release
  charts/external-dns-management/doc.go
  examples/gardener-controllerregistration.yaml
Labels: kind/cleanup, needs/ok-to-test

#106 fixing dnsinfo addallsplitted semantics
  pkg/dns/source/dnsinfo.go
Labels: needs/ok-to-test
