Repository gardener/external-dns-management, pull requests merged in 2020-12, with the labels that each got.

#142 updated canonical hosted zones for creating AWS alias targets
  pkg/controller/provider/aws/aliastarget.go
Labels: kind/enhancement, needs/ok-to-test, needs/review, size/xs

#144 run make release in dockerfile
  build/Dockerfile
Labels: needs/ok-to-test, needs/review, size/xs

#120 Update README.md
  README.md
  pkg/dns/provider/controller.go
Labels: lifecycle/stale, needs/changes, needs/ok-to-test, size/xs
