Repository gardener/external-dns-management, pull requests merged in 2021-06, with the labels that each got.

#183 Use AWS SDK config's `MaxRetries` instead of own paging to avoid throttling errors
  README.md
  charts/external-dns-management/templates/deployment.yaml
  charts/external-dns-management/values.yaml
  pkg/controller/provider/aws/factory.go
  pkg/controller/provider/aws/handler.go
  pkg/controller/provider/aws/handler_zonestatepaging.go
  pkg/dns/provider/advancedopts.go
  pkg/dns/provider/config.go
  pkg/dns/provider/const.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#184 Add DNSProvider replication controller
  cmd/compound/main.go
  cmd/dedicated/main.go
  pkg/controller/replication/dnsprovider/controller.go
  pkg/controller/replication/dnsprovider/handler.go
  pkg/controller/replication/dnsprovider/slaves.go
  pkg/dns/const.go
  pkg/dns/source/reconciler.go
  pkg/dns/source/utils.go
  vendor/github.com/gardener/controller-manager-library/hack/run-in.sh
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#186 Revendor controller-manager-library to fix namespaced shared informers
  go.mod
  go.sum
  pkg/dns/source/dnsinfo.go
  vendor/github.com/gardener/controller-manager-library/hack/run-in.sh
  vendor/github.com/gardener/controller-manager-library/pkg/resources/informers.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, size/xs

#189 update golang@1.16.5
  build/Dockerfile
Labels: needs/ok-to-test, needs/review, size/xs

#188 fix concurrent access to filter in sharedFilteredInformerFactory
  go.mod
  go.sum
  vendor/github.com/gardener/controller-manager-library/pkg/resources/informers.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, size/xs

#185 expiration for dns owners
  .gitignore
  charts/external-dns-management/templates/crds.yaml
  examples/10-crds.yaml
  examples/controller-registration.yaml
  pkg/apis/dns/crds/dns.gardener.cloud_dnsowners.yaml
  pkg/apis/dns/crds/zz_generated_crds.go
  pkg/apis/dns/v1alpha1/dnsowner.go
  pkg/apis/dns/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/provider/aws/factory.go
  pkg/dns/provider/init_test.go
  pkg/dns/provider/ownercache.go
  pkg/dns/provider/ownercache_test.go
  pkg/dns/provider/provider_suite_test.go
  pkg/dns/provider/state.go
  pkg/dns/provider/state_owner.go
  pkg/dns/utils/schedule.go
  pkg/dns/utils/schedule_test.go
  pkg/dns/utils/utils_owner.go
  pkg/dns/utils/utils_suite_test.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#190 Credentials documentation for providers azure-dns, alicloud-dns and openstack-designate
  README.md
  docs/alicloud-dns/README.md
  docs/azure-dns/README.md
  docs/openstack-designate/README.md
  examples/20-secret-azure-credentials.yaml
Labels: needs/ok-to-test, needs/review, size/m

#164 Adds Artifacts for Landscaper Integration
  .ci/component_descriptor
  .landscaper/blueprint/blueprint.yaml
  .landscaper/blueprint/deploy-executions.yaml
  .landscaper/resources.yaml
Labels: lifecycle/rotten, needs/changes, needs/ok-to-test, needs/review, size/m

#191 Added `DNSHostedZonePolicy` resource to set zone specific zone state cache TTL
  charts/external-dns-management/doc.go
  charts/external-dns-management/templates/clusterrole.yaml
  charts/external-dns-management/templates/crds.yaml
  examples/10-crds.yaml
  examples/80-dnshostedzonepolicy.yaml
  examples/controller-registration.yaml
  hack/generate-controller-registration.sh
  pkg/apis/dns/crds/dns.gardener.cloud_dnshostedzonepolicies.yaml
  pkg/apis/dns/crds/zz_generated_crds.go
  pkg/apis/dns/v1alpha1/dnshostedzonepolicy.go
  pkg/apis/dns/v1alpha1/register.go
  pkg/apis/dns/v1alpha1/zz_generated.deepcopy.go
  pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/dns_client.go
  pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/dnshostedzonepolicy.go
  pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/fake/fake_dns_client.go
  pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/fake/fake_dnshostedzonepolicy.go
  pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/generated_expansion.go
  pkg/client/dns/informers/externalversions/dns/v1alpha1/dnshostedzonepolicy.go
  pkg/client/dns/informers/externalversions/dns/v1alpha1/interface.go
  pkg/client/dns/informers/externalversions/generic.go
  pkg/client/dns/listers/dns/v1alpha1/dnshostedzonepolicy.go
  pkg/client/dns/listers/dns/v1alpha1/expansion_generated.go
  pkg/controller/provider/openstack/handler_test.go
  pkg/dns/provider/config.go
  pkg/dns/provider/context.go
  pkg/dns/provider/controller.go
  pkg/dns/provider/provider.go
  pkg/dns/provider/state.go
  pkg/dns/provider/state_provider.go
  pkg/dns/provider/state_zone.go
  pkg/dns/provider/state_zonepolicy.go
  pkg/dns/provider/zone.go
  pkg/dns/provider/zonecache.go
  pkg/dns/utils/utils_zonepolicy.go
  vendor/github.com/gardener/controller-manager-library/hack/run-in.sh
Labels: needs/changes, needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#193 Makefile extension landscaper
  Makefile
  hack/create-installation.sh
  hack/generate-cd.sh
  hack/get-cd-component-name.sh
  hack/get-cd-registry.sh
  hack/get-image-registry.sh
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#194 Deploying DNSHostedZonePolicy in helm chart
  charts/external-dns-management/templates/hostedzonepolicies.yaml
  charts/external-dns-management/values.yaml
  examples/80-dnshostedzonepolicy.yaml
  examples/controller-registration.yaml
Labels: needs/ok-to-test, needs/review, size/s

#196 using configmaps and leases for leader election
  README.md
  charts/external-dns-management/templates/deployment.yaml
  charts/external-dns-management/templates/role.yaml
  charts/external-dns-management/values.yaml
  cmd/compound/main.go
  cmd/dedicated/main.go
  examples/controller-registration.yaml
  go.mod
  go.sum
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/controller.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/lease.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/lease/config.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/lease/lease.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/syncer.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/watches/constraints.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/watches/interface.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl
