Repository gardener/external-dns-management, pull requests merged in 2021-03, with the labels that each got.

#157 Add PriorityClass for extension Pods
  charts/external-dns-management/templates/_helpers.tpl
  charts/external-dns-management/templates/deployment.yaml
  charts/external-dns-management/templates/priorityclass.yaml
  charts/external-dns-management/values.yaml
  examples/controller-registration.yaml
Labels: area/high-availability, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#158 improve error message for 'no domain matching zones'
  pkg/dns/provider/provider.go
  pkg/dns/provider/selection/selection.go
  pkg/dns/provider/selection/selection_test.go
Labels: needs/ok-to-test, needs/review, size/xs

#159 helm charts: no deployment of CRDs by default
  charts/external-dns-management/templates/vpa.yaml
  charts/external-dns-management/values.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#160 consider provider zone on adding entries to zone
  pkg/controller/provider/openstack/handler_test.go
  pkg/dns/provider/default.go
  pkg/dns/provider/entry.go
  pkg/dns/provider/interface.go
  pkg/dns/provider/provider.go
  pkg/dns/provider/state.go
  pkg/dns/provider/state_entry.go
  pkg/dns/provider/state_zone.go
  pkg/dns/provider/utils.go
  pkg/dns/provider/zone.go
Labels: needs/ok-to-test, needs/review, size/m

#162 do not remove entry finalizer if provider backend is temporarily unavailable during reconciliation
  pkg/dns/provider/state_entry.go
  pkg/dns/provider/statusupdate.go
Labels: needs/ok-to-test, needs/review, size/xs
