Repository gardener/external-dns-management, pull requests merged in 2021-02, with the labels that each got.

#152 GCP Cloud DNS documentation
  docs/google-cloud-dns/README.md
Labels: needs/ok-to-test, needs/review, size/s

#150 activating compound dnscontroller
  .github/pull_request_template.md
  .gitignore
  Makefile
  README.md
  VERSION
  charts/external-dns-management/templates/deployment.yaml
  charts/external-dns-management/values.yaml
  cmd/compound/main.go
  cmd/dedicated/main.go
  docs/aws-route53/README.md
  docs/google-cloud-dns/README.md
  examples/controller-registration.yaml
  test/functional/basics.go
  test/functional/config/config.go
  test/functional/run.sh
Labels: kind/api-change, needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#153 reduce logging during provider deletion
  pkg/dns/provider/state_provider.go
Labels: needs/ok-to-test, needs/review, size/xs

#155 infoblox: fix panic on setting value for unexported field certPool
  pkg/controller/provider/infoblox/handler.go
Labels: needs/ok-to-test, needs/review, size/xs

#156 infoblox: add optional CA_CERT to credential
  pkg/controller/provider/infoblox/handler.go
Labels: needs/ok-to-test, needs/review, size/xs
