Repository gardener/external-dns-management, pull requests merged in 2021-07, with the labels that each got.

#197 Fix blueprint for landscaper based deployment of component dns-external
  .landscaper/blueprint/deploy-executions.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#198 Landscaper based deployment: change updateStrategy from patch to update
  .landscaper/blueprint/deploy-executions.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#199 Feature: IPv6 Support
  pkg/controller/provider/alicloud/access.go
  pkg/controller/provider/azure/execution.go
  pkg/controller/provider/cloudflare/access.go
  pkg/controller/provider/infoblox/access.go
  pkg/controller/provider/netlify/access.go
  pkg/controller/provider/openstack/handler.go
  pkg/dns/provider/changemodel.go
  pkg/dns/provider/entry.go
  pkg/dns/provider/raw/execution.go
  pkg/dns/provider/target.go
  pkg/dns/records.go
  pkg/dns/utils.go
  test/functional/basics.go
Labels: needs/changes, needs/ok-to-test, needs/review, size/m

#201 stop using pkg/errors
  go.mod
  pkg/controller/provider/infoblox/handler.go
  pkg/controller/replication/dnsprovider/handler.go
  pkg/controller/replication/dnsprovider/slaves.go
  pkg/dns/provider/config.go
  pkg/dns/provider/errors/handlererror.go
  pkg/dns/provider/provider.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, size/s
