Repository gardener/external-dns-management, pull requests merged in 2021-09, with the labels that each got.

#207 Fix provider domain selection: allow final dot and uppercase
  build/Dockerfile
  pkg/dns/provider/selection/selection.go
  pkg/dns/provider/selection/selection_test.go
Labels: needs/ok-to-test, needs/review, size/s

#208 Support for Kubernetes v1.22
  charts/external-dns-management/templates/clusterrole.yaml
  charts/external-dns-management/templates/clusterrolebinding.yaml
  charts/external-dns-management/templates/crds-v1.yaml
  charts/external-dns-management/templates/crds-v1beta1.yaml
  charts/external-dns-management/templates/role.yaml
  charts/external-dns-management/templates/rolebinding.yaml
  cmd/compound/main.go
  cmd/dedicated/main.go
  examples/10-crds.yaml
  examples/11-crd-dnse-val.yaml
  examples/11-crd-dnspr-val.yaml
  examples/50-ingress-with-dns.yaml
  examples/controller-registration.yaml
  go.mod
  go.sum
  pkg/controller/source/ingress/handler.go
  vendor/github.com/gardener/controller-manager-library/hack/run-in.sh
  vendor/github.com/gardener/controller-manager-library/pkg/resources/apiextensions/crds.go
  vendor/github.com/gardener/controller-manager-library/pkg/resources/apiextensions/versions.go
  vendor/github.com/gardener/controller-manager-library/pkg/resources/slavecache.go
  vendor/modules.txt
Labels: needs/ok-to-test, reviewed/lgtm, size/xl

#209 Fix apiVersion for rbac
  charts/external-dns-management/templates/clusterrole.yaml
  charts/external-dns-management/templates/clusterrolebinding.yaml
  charts/external-dns-management/templates/role.yaml
  charts/external-dns-management/templates/rolebinding.yaml
Labels: needs/review, size/xs

#210 Relative links
  README.md
Labels: reviewed/lgtm, size/xs

#212 Fix data race for objects from slave cache
  examples/controller-registration.yaml
  go.mod
  go.sum
  vendor/github.com/gardener/controller-manager-library/hack/generate-crds
  vendor/github.com/gardener/controller-manager-library/hack/run-in.sh
  vendor/github.com/gardener/controller-manager-library/pkg/resources/subcache.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, size/xs

#213 Fix provider zones check if forwarded subdomain included
  pkg/controller/provider/mock/handler.go
  pkg/dns/provider/provider.go
  test/integration/privateZones_test.go
  test/integration/testenv.go
Labels: needs/ok-to-test, needs/review, size/s

#215 Avoid restarts on throttling due to failed health checks
  go.mod
  go.sum
  pkg/dns/provider/changemodel.go
  pkg/dns/provider/context.go
  pkg/dns/provider/controller.go
  pkg/dns/provider/entry.go
  pkg/dns/provider/state.go
  pkg/dns/provider/state_entry.go
  pkg/dns/provider/state_zone.go
  pkg/dns/provider/ticker.go
  pkg/dns/utils/trylock.go
  pkg/dns/utils/trylock_test.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/interface.go
  vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/pool.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/changes, needs/review, needs/second-opinion, size/l

#214 Use current owners in change model
  pkg/dns/dnsset.go
  pkg/dns/provider/changemodel.go
  pkg/dns/provider/ownercache.go
  pkg/dns/provider/state.go
  pkg/dns/provider/state_provider.go
  pkg/dns/provider/state_zone.go
Labels: needs/ok-to-test, needs/changes, needs/review, size/s

#216 added flag `--blocked-zone` to allow ignoring zones on provider handler level
  README.md
  charts/external-dns-management/templates/deployment.yaml
  charts/external-dns-management/values.yaml
  examples/controller-registration.yaml
  hack/generateChartOptions.py
  pkg/controller/provider/alicloud/handler.go
  pkg/controller/provider/aws/handler.go
  pkg/controller/provider/azure/handler.go
  pkg/controller/provider/cloudflare/handler.go
  pkg/controller/provider/google/handler.go
  pkg/controller/provider/infoblox/handler.go
  pkg/controller/provider/netlify/handler.go
  pkg/controller/provider/openstack/handler.go
  pkg/controller/provider/openstack/handler_test.go
  pkg/dns/provider/advancedopts.go
  pkg/dns/provider/const.go
  test/functional/config/utils.go
  test/functional/run.sh
Labels: needs/ok-to-test, needs/review, size/m
