Repository gardener/external-dns-management, pull requests merged in 2021-05, with the labels that each got.

#172 Ensure stable provider result in method DNSProviders.LookupFor
  pkg/dns/provider/provider.go
Labels: needs/ok-to-test, needs/review, size/xs

#173 Added requests_per_zone and zone_cache_discardings metrics
  pkg/controller/provider/alicloud/access.go
  pkg/controller/provider/alicloud/handler.go
  pkg/controller/provider/aws/execution.go
  pkg/controller/provider/aws/handler.go
  pkg/controller/provider/azure/execution.go
  pkg/controller/provider/azure/handler.go
  pkg/controller/provider/cloudflare/access.go
  pkg/controller/provider/google/execution.go
  pkg/controller/provider/google/handler.go
  pkg/controller/provider/infoblox/access.go
  pkg/controller/provider/infoblox/handler.go
  pkg/controller/provider/netlify/access.go
  pkg/controller/provider/openstack/designateclient.go
  pkg/controller/provider/openstack/handler_test.go
  pkg/dns/provider/inmemory.go
  pkg/dns/provider/interface.go
  pkg/dns/provider/provider.go
  pkg/dns/provider/raw/execution.go
  pkg/dns/provider/utils.go
  pkg/dns/provider/zonecache.go
  pkg/server/metrics/metrics.go
Labels: needs/ok-to-test, needs/review, size/m

#175 Update README.md
  docs/cloudflare/README.md
Labels: needs/review, size/xs

#178 Only reconcile affected zones on owner changes to reduce work load
  pkg/dns/dnsset.go
  pkg/dns/provider/changemodel.go
  pkg/dns/provider/state.go
  pkg/dns/provider/state_owner.go
  pkg/dns/provider/state_zone.go
  pkg/dns/provider/zone.go
Labels: needs/ok-to-test, needs/review, size/s

#180 fix dnsannotation handling
  pkg/dns/source/dnsinfo.go
Labels: needs/ok-to-test, needs/review, size/s

#181 Own implementation for paging AWS zone state to properly deal with throttling
  go.mod
  go.sum
  pkg/controller/provider/aws/handler.go
  pkg/controller/provider/aws/handler_zonestatepaging.go
  pkg/dns/provider/config.go
  pkg/dns/provider/factory.go
  pkg/dns/provider/provider.go
  vendor/github.com/aws/aws-sdk-go/aws/client/client.go
  vendor/github.com/aws/aws-sdk-go/aws/client/logger.go
  vendor/github.com/aws/aws-sdk-go/aws/config.go
  vendor/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/ssocreds/doc.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/ssocreds/os.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/ssocreds/os_windows.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/ssocreds/provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/v3model.go
  vendor/github.com/aws/aws-sdk-go/aws/session/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/session/session.go
  vendor/github.com/aws/aws-sdk-go/aws/session/shared_config.go
  vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/host.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/jsonrpc/jsonrpc.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/jsonrpc/unmarshal_error.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/restjson/restjson.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/restjson/unmarshal_error.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/build.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/xml_to_struct.go
  vendor/github.com/aws/aws-sdk-go/service/route53/api.go
  vendor/github.com/aws/aws-sdk-go/service/route53/errors.go
  vendor/github.com/aws/aws-sdk-go/service/sso/api.go
  vendor/github.com/aws/aws-sdk-go/service/sso/doc.go
  vendor/github.com/aws/aws-sdk-go/service/sso/errors.go
  vendor/github.com/aws/aws-sdk-go/service/sso/service.go
  vendor/github.com/aws/aws-sdk-go/service/sso/ssoiface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/sts/api.go
  vendor/github.com/gardener/controller-manager-library/hack/run-in.sh
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, size/m
