Repository gardener/external-dns-management, pull requests merged in 2022-04, with the labels that each got.

#244 Update to golang 1.17.8 and alpine 3.15.3
  build/Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#245 Fix sporadic panic on starting remote access server.
  pkg/server/remote/embed/dynamictransportcreds.go
  pkg/server/remote/server.go
Labels: needs/ok-to-test, needs/review, size/xs

#246 Ignore already deleted or created changes in aws route53
  pkg/controller/provider/aws/execution.go
Labels: needs/ok-to-test, needs/review, size/m
