Repository gardener/external-dns-management, pull requests merged in 2022-10, with the labels that each got.

#280 Landscaper Cleanup
  .ci/component_descriptor
  .ci/resources.yaml
  .landscaper/blueprint/blueprint.yaml
  .landscaper/blueprint/deploy-executions.yaml
  .landscaper/resources.yaml
  Makefile
  hack/create-installation.sh
Labels: reviewed/lgtm, size/m

#279 Ignore slave objects of non-responsible DNS classes
  pkg/dns/source/reconciler.go
  pkg/dns/source/slaves.go
Labels: needs/ok-to-test

#282 fixing tiny tiny typo
  README.md
Labels: reviewed/lgtm, size/xs
