Repository gardener/external-dns-management, pull requests merged in 2022-05, with the labels that each got.

#248 Cleanup Token Projection artefacts
  charts/external-dns-management/templates/deployment.yaml
  charts/external-dns-management/templates/serviceaccount.yaml
  examples/controller-registration.yaml
Labels: area/open-source, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#249 Update base/build image
  Makefile
  build/Dockerfile
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/README
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/errors.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/huffman.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/idna/go118.go
  vendor/golang.org/x/net/idna/idna10.0.0.go
  vendor/golang.org/x/net/idna/idna9.0.0.go
  vendor/golang.org/x/net/idna/pre_go118.go
  vendor/golang.org/x/net/idna/punycode.go
  vendor/golang.org/x/net/internal/socket/complete_dontwait.go
  vendor/golang.org/x/net/internal/socket/complete_nodontwait.go
  vendor/golang.org/x/net/internal/socket/empty.s
  vendor/golang.org/x/net/internal/socket/rawconn_mmsg.go
  vendor/golang.org/x/net/internal/socket/rawconn_msg.go
  vendor/golang.org/x/net/publicsuffix/table.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, size/xs

#250 Fix domain name comparison in tryFixChanges
  pkg/controller/provider/aws/execution.go
Labels: needs/ok-to-test, needs/review, size/xs

#252 Delete cached dnsactivations on deleting dnsowner
  pkg/dns/provider/controller.go
  pkg/dns/provider/ownercache.go
  pkg/dns/provider/ownercache_test.go
  pkg/dns/provider/state_owner.go
  pkg/server/remote/conversion/conversion_test.go
Labels: needs/ok-to-test, needs/review, size/xs

#257 Don't cleanup entries belonging to provider of equivalent zone
  pkg/dns/provider/changemodel.go
  pkg/dns/provider/interface.go
  pkg/dns/provider/provider.go
  pkg/dns/provider/state.go
  pkg/dns/provider/state_zone.go
Labels: needs/ok-to-test, needs/review, size/s
