Repository gardener/external-dns-management, pull requests merged in 2023-10, with the labels that each got.

#320 Introduction of Infoblox extensible attributes
  docs/infoblox/README.md
  pkg/controller/provider/infoblox/access.go
  pkg/controller/provider/infoblox/handler.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#321 Additional AWS regions with canonical hosted zones for ELBs
  pkg/controller/provider/aws/aliastarget.go
Labels: needs/ok-to-test, needs/review, size/xs

#322 Update AWS canonical hosted zones from external-dns repo
  pkg/controller/provider/aws/aliastarget.go
Labels: needs/ok-to-test, needs/review, size/m

#326 Increase rsa key size to 3072 bits
  pkg/controller/remoteaccesscertificates/certificate.go
  pkg/controller/remoteaccesscertificates/controller.go
  pkg/server/remote/embed/remoteserver.go
  test/integration/suite_test.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
