Repository gardener/external-dns-management, pull requests merged in 2023-09, with the labels that each got.

#315 add imagePullSecrets option to deployment
  charts/external-dns-management/templates/deployment.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#316 Allow to create DNSEntries for hosted zone base domain
  pkg/dns/mapping.go
  pkg/dns/mapping_test.go
  pkg/dns/provider/entry.go
  test/functional/basics.go
Labels: needs/ok-to-test, needs/review, size/s

#317 Automate golang version updates
  .github/dependabot.yaml
Labels: needs/review, size/xs
