Repository gardener/external-dns-management, pull requests merged in 2023-12, with the labels that each got.

#339 Prepare gcr to ar
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#342 switch GCR -> Artifact-Registry
  .ci/pipeline_definitions
  Makefile
  charts/external-dns-management/values.yaml
  hack/.ci/component_descriptor
  hack/get-cd-registry.sh
  hack/get-image-registry.sh
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#343 Revert "Makefile extension landscaper (#193)"
  Makefile
  hack/generate-cd.sh
  hack/get-cd-component-name.sh
  hack/get-cd-registry.sh
  hack/get-image-registry.sh
Labels: needs/ok-to-test, needs/review, size/m

#341 [AWS Route53] Create alias AAAA records for load balancers if target domain name has an IPv6 address
  pkg/controller/provider/aws/aliastarget.go
  pkg/controller/provider/aws/execution.go
  test/functional/basics.go
  test/functional/config/config.go
Labels: needs/ok-to-test, needs/review, size/m

#347 rfc2136 provider: expect base64 encoded TSIG key
  go.mod
  pkg/controller/provider/rfc2136/execution.go
  pkg/controller/provider/rfc2136/handler.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#348 [aws-route53] Move canonicalhostedzone map to own package
  pkg/controller/provider/aws/aliastarget.go
  pkg/controller/provider/aws/data/canonicalhostedzones.go
Labels: needs/ok-to-test, needs/review, size/m
