Repository gardener/external-dns-management, pull requests merged in 2024-11, with the labels that each got.

#397 Update controller-manager-library dependency
  .reuse/dep5
  Makefile
  REUSE.toml
  charts/external-dns-management/templates/crds.yaml
  go.mod
  go.sum
  hack/generate-code
  pkg/apis/dns/crds/dns.gardener.cloud_dnsannotations.yaml
  pkg/apis/dns/crds/dns.gardener.cloud_dnsentries.yaml
  pkg/apis/dns/crds/dns.gardener.cloud_dnshostedzonepolicies.yaml
  pkg/apis/dns/crds/dns.gardener.cloud_dnsowners.yaml
  pkg/apis/dns/crds/dns.gardener.cloud_dnsproviders.yaml
  pkg/apis/dns/crds/zz_generated_crds.go
  pkg/client/dns/clientset/versioned/fake/clientset_generated.go
  pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/dnsannotation.go
  pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/dnsentry.go
  pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/dnshostedzonepolicy.go
  pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/dnsowner.go
  pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/dnsprovider.go
  pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/fake/fake_dnsannotation.go
  pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/fake/fake_dnsentry.go
  pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/fake/fake_dnshostedzonepolicy.go
  pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/fake/fake_dnsowner.go
  pkg/client/dns/clientset/versioned/typed/dns/v1alpha1/fake/fake_dnsprovider.go
  pkg/client/dns/informers/externalversions/factory.go
  pkg/client/dns/listers/dns/v1alpha1/dnsannotation.go
  pkg/client/dns/listers/dns/v1alpha1/dnsentry.go
  pkg/client/dns/listers/dns/v1alpha1/dnshostedzonepolicy.go
  pkg/client/dns/listers/dns/v1alpha1/dnsowner.go
  pkg/client/dns/listers/dns/v1alpha1/dnsprovider.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#399 chore: Remove obsolete Make target adjust-install-gosec.sh
  Makefile
Labels: kind/cleanup, needs/ok-to-test, needs/review, size/xs

#400 Use AWS SDK v2
  go.mod
  go.sum
  hack/sast.sh
  pkg/controller/provider/alicloud/state.go
  pkg/controller/provider/aws/aliastarget.go
  pkg/controller/provider/aws/execution.go
  pkg/controller/provider/aws/handler.go
  pkg/controller/provider/aws/routingpolicy.go
  pkg/controller/provider/cloudflare/access.go
  pkg/controller/provider/cloudflare/state.go
  pkg/controller/provider/infoblox/access.go
  pkg/controller/provider/infoblox/state.go
  pkg/controller/provider/netlify/access.go
  pkg/controller/provider/netlify/state.go
  pkg/controller/provider/powerdns/execution.go
  pkg/controller/provider/rfc2136/execution.go
  pkg/dns/provider/dedicatedrecord.go
  pkg/dns/provider/raw/execution.go
  pkg/dns/provider/raw/records.go
  pkg/dns/provider/state_entry.go
  pkg/dns/utils/utils_dns.go
  pkg/server/remote/conversion/conversion.go
  test/functional/config/utils.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xl
