Repository gardener/external-dns-management, pull requests merged in 2025-03, with the labels that each got.

#417 Bump golang to 1.24 in CI/CD pipeline
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#419 Fix field name LastUpdateTime
  pkg/apis/dns/v1alpha1/dnsentry.go
  pkg/apis/dns/v1alpha1/zz_generated.deepcopy.go
  pkg/dns/provider/entry.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#420 Fix field name LastUpdateTime for DNSProvider
  pkg/apis/dns/v1alpha1/dnsprovider.go
  pkg/apis/dns/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/replication/dnsprovider/slaves.go
  pkg/dns/provider/provider.go
  pkg/dns/utils/utils.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#424 chore: Add copyright profile for GoLand
  .gitignore
  .idea/copyright/Gardener.xml
  .idea/copyright/profiles_settings.xml
Labels: area/dev-productivity, area/open-source, kind/enhancement, needs/review, size/xs

#426 ci: Unify `make format`
  .ci/pipeline_definitions
  .ci/verify
  Makefile
Labels: kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
