Repository gardener/external-dns-management, pull requests merged in 2025-07, with the labels that each got.

#554 Fix panic on startup if `DNSEntry` is annotated to be ignored
  pkg/dns/provider/state_entry.go
Labels: kind/bug, reviewed/ok-to-test, size/XS, cla: yes, lgtm, approved

#569 Revert "Fix sporadic failing updates on switching entries between simple and weighted routing policy (#524)"
  hack/tools/loadtest/main.go
  pkg/dns/provider/entry.go
  pkg/dns/provider/state.go
  pkg/dns/provider/state_entry.go
  pkg/dns/provider/state_zone.go
  test/integration/compound/compound_test.go
  test/integration/ingressAnnotation_test.go
Labels: needs/ok-to-test, size/L, do-not-merge/needs-kind, cla: yes

#570 Fix panic on startup if `DNSEntry` is ignored (#554)
  pkg/dns/provider/state_entry.go
Labels: reviewed/ok-to-test, size/XS, do-not-merge/needs-kind, cla: yes

#561 export testresults as inlined ocm-resource
  .github/workflows/build.yaml
Labels: kind/task, reviewed/ok-to-test, size/M, cla: yes, lgtm, approved, skip-review

#566 chore: Add `/kind` categorization to PR template
  .github/pull_request_template.md
Labels: kind/task, reviewed/ok-to-test, size/S, cla: yes, lgtm, approved

#564 feat: Validate `DNSEntry` data fields
  charts/external-dns-management/templates/crds.yaml
  pkg/apis/dns/crds/dns.gardener.cloud_dnsentries.yaml
  pkg/apis/dns/crds/zz_generated_crds.go
  pkg/apis/dns/v1alpha1/dnsentry.go
  pkg/dnsman2/apis/dns/crd-dns.gardener.cloud_dnsentries.yaml
  pkg/dnsman2/controller/dnsentry/reconciler_reconcile.go
  pkg/dnsman2/controller/dnsentry/reconciler_test.go
Labels: kind/task, reviewed/ok-to-test, size/L, cla: yes, lgtm, approved

#576 increase powerdns apiKey max lenght
  pkg/controller/provider/powerdns/factory.go
Labels: kind/bug, kind/enhancement, reviewed/ok-to-test, size/XS, cla: yes, lgtm, approved, ok-to-test
