Repository gardener/external-dns-management, pull requests merged in 2025-05, with the labels that each got.

#457 chore: Add make target check-imports
  Makefile
  cmd/compound/.import-restrictions
  cmd/dnsman2/.import-restrictions
  pkg/apis/.import-restrictions
  pkg/client/.import-restrictions
  pkg/controller/.import-restrictions
  pkg/dns/.import-restrictions
  pkg/dnsman2/.import-restrictions
  pkg/server/.import-restrictions
Labels: kind/enhancement, kind/task, needs/ok-to-test, reviewed/lgtm, size/s

#458 Periodic feedback events on errors
  pkg/dns/source/defaults.go
  pkg/dns/source/feedback.go
  pkg/dns/source/slaves.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#460 Clean up google-clouddns handler initialisation
  pkg/controller/provider/google/handler.go
  pkg/controller/provider/google/handler_test.go
Labels: needs/ok-to-test, needs/review, size/s

#465 cleanup: drop unused (and outdated) script
  hack/.ci/component_descriptor
Labels: needs/ok-to-test, needs/review, reviewed/lgtm, size/s

#466 Fix heuristics for old entries without `generateName` field
  pkg/dns/source/filterbykindreonciler.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#468 Add `OWNERS` and `OWNERS_ALIASES`
  OWNERS
  OWNERS_ALIASES
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#469 Introduce make target `test-integration`
  Makefile
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#470 CI/CD steps `test` and `integrationtests` moved to prow
  .ci/pipeline_definitions
  go.mod
  go.sum
  hack/tools.go
  pkg/dns/provider/lookupprocessor_test.go
  pkg/dns/utils/trylock_test.go
Labels: kind/task, needs/ok-to-test, reviewed/ok-to-test, size/l, cla: yes, lgtm, approved

#472 Remove tests from make target `verify-extended`
  Makefile
Labels: kind/task, needs/ok-to-test, reviewed/ok-to-test, size/xs, cla: yes, lgtm, approved

#471 Use Renovate instead of Dependabot
  .github/dependabot.yaml
  Makefile
  hack/generate-renovate-ignore-deps.sh
  pkg/dns/utils/trylock_test.go
  renovate.json5
Labels: kind/task, needs/ok-to-test, reviewed/ok-to-test, size/l, cla: yes, lgtm, approved

#481 Update `openstack-designate` provider library `gophercloud`
  go.mod
  go.sum
  pkg/controller/provider/openstack/designateclient.go
  pkg/controller/provider/openstack/execution.go
  pkg/controller/provider/openstack/handler.go
  pkg/controller/provider/openstack/handler_test.go
  renovate.json5
Labels: kind/task, needs/ok-to-test, reviewed/ok-to-test, size/L, cla: yes, lgtm, approved
